wandb_version: 1

Scheduler:
  desc: null
  value: StepLR
_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.5
      5: 0.10.25
      8:
      - 1
      - 5
architecture:
  desc: null
  value: EGC
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: DG15x15L2D
epochs:
  desc: null
  value: 1000
hidden_dim:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.01
num_layers:
  desc: null
  value: 4
seed_num:
  desc: null
  value: 24
test_size:
  desc: null
  value: 334
torch_seed:
  desc: null
  value: 24
total_fold:
  desc: null
  value: 3
train_size:
  desc: null
  value: 666
